[[redirects]]
    from = "/api"
    to = "https://poetic-raindrop-e6e98a.netlify.app/api"
    status = 200
    force = true

[[redirects]]
    from = "/api/:match*"
    to = "https://poetic-raindrop-e6e98a.netlify.app/api/:match*"
    status = 200
    force = true

[[redirects]]
    from = "/route"
    to = "https://poetic-raindrop-e6e98a.netlify.app/route"
    status = 200
    force = true

[[redirects]]
    from = "/route/:match*"
    to = "https://poetic-raindrop-e6e98a.netlify.app/route/:match*"
    status = 200
    force = true

[[redirects]]
    from = "/"
    to = "https://poetic-raindrop-e6e98a.netlify.app/"
    status = 200
    force = true

[[redirects]]
    from = "/:match*"
    to = "https://poetic-raindrop-e6e98a.netlify.app/:match*"
    status = 200
    force = true