# Redirect API requests to serverless functions
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

# Example of handling custom routes - adjust based on the use case of the 'route' folder
[[redirects]]
    from = "/special-route/*"
    to = "/.netlify/functions/special-handler/:splat"
    status = 200

# Serve static content from the 'www' folder for any other requests
[[redirects]]
    from = "/www/*"
    to = "/:splat"
    status = 200
