[[redirects]]
    from = "/api"
    to = "/api"
    status = 200
    force = true

[[redirects]]
    from = "/api/:match*"
    to = "/api/:match*"
    status = 200
    force = true

[[redirects]]
    from = "/route"
    to = "/route"
    status = 200
    force = true

[[redirects]]
    from = "/route/:match*"
    to = "/route/:match*"
    status = 200
    force = true

[[redirects]]
    from = "/"
    to = "/"
    status = 200
    force = true

[[redirects]]
    from = "/:match*"
    to = "/:match*"
    status = 200
    force = true