[[redirects]]
    from = "/api"
    to = "https://project3.vercel.app/api"
    status = 200
    force = true

[[redirects]]
    from = "/api/:match*"
    to = "https://project3.vercel.app/api/:match*"
    status = 200
    force = true

[[redirects]]
    from = "/route"
    to = "https://project2.vercel.app/route"
    status = 200
    force = true

[[redirects]]
    from = "/route/:match*"
    to = "https://project2.vercel.app/route/:match*"
    status = 200
    force = true

[[redirects]]
    from = "/"
    to = "https://project1.vercel.app/"
    status = 200
    force = true

[[redirects]]
    from = "/:match*"
    to = "https://project1.vercel.app/:match*"
    status = 200
    force = true